# Generated by Django 3.0.5 on 2020-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200413_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
