# Generated by Django 3.0.5 on 2020-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200417_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
