# Generated by Django 3.0.5 on 2020-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0004_animal_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars/%Y/%m/%d'),
        ),
    ]
